# Example Site settings
url: "https://choc0villain.github.io/"
#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.mdn

nav:
 - title: about
    url: /about

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag


minimal_mistakes_skin: "sunrise"